import Foundation

/// Generation templates for topic syntheses beyond the shared magazine pipeline. Each one
/// asks the model for a different content structure in a single call over the collected
/// sources; "auto" lets the model pick one first.
enum DeepReadSynthesisTemplate: String, CaseIterable, Identifiable {
    case auto = "deepread_auto"
    case brief = "deepread_brief"
    case qa = "deepread_qa"
    case debate = "deepread_debate"
    case timeline = "deepread_timeline"
    case review = "deepread_review"

    var id: String { rawValue }

    /// Templates the model may pick in auto mode (plus the classic magazine).
    static let concrete: [DeepReadSynthesisTemplate] = [.brief, .qa, .debate, .timeline, .review]

    /// Every built-in generation template in display order: auto, the shared magazine pair, then these.
    static var options: [(id: String, name: String, detail: String, symbol: String)] {
        [(auto.id, auto.name, auto.detail, auto.symbol)]
            + IOSDeepReadTemplate.builtIns.map { ($0.id, $0.name, $0.id == IOSDeepReadTemplate.editorial.id ? "斜切头图与文中配图的图文版。" : "纯文字杂志长文：时间轴、脉络、分析与延伸阅读。",
                                                  $0.id == IOSDeepReadTemplate.editorial.id ? "photo.on.rectangle" : "newspaper") }
            + concrete.map { ($0.id, $0.name, $0.detail, $0.symbol) }
    }

    var name: String {
        switch self {
        case .auto: "自动"
        case .brief: "速览简报"
        case .qa: "问答解读"
        case .debate: "观点交锋"
        case .timeline: "时间线报道"
        case .review: "评测汇总"
        }
    }

    var detail: String {
        switch self {
        case .auto: "读完资料后由 Agent 选择最合适的模板。"
        case .brief: "5 条要点、背景、影响与待核实，更快更省。"
        case .qa: "读者最关心的问题，逐一回答并标注来源。"
        case .debate: "核心争议、各方阵营与原话，以及你可以怎么看。"
        case .timeline: "带来源的详细时间节点，解读转折点。"
        case .review: "多家评测的共识与分歧、规格和打分对照。"
        }
    }

    var symbol: String {
        switch self {
        case .auto: "wand.and.stars"
        case .brief: "bolt.horizontal"
        case .qa: "questionmark.bubble"
        case .debate: "person.2.wave.2"
        case .timeline: "calendar.day.timeline.left"
        case .review: "checklist"
        }
    }

    /// When to use it, for the auto-pick prompt.
    var useWhen: String {
        switch self {
        case .auto: ""
        case .brief: "一般新闻，读者只想快速了解"
        case .qa: "政策、新技术、规则变化或复杂事件，读者有很多疑问"
        case .debate: "存在明显争议、多方立场对立"
        case .timeline: "持续发酵、有多个时间节点的事件"
        case .review: "新产品或服务发布，有多家评测"
        }
    }
}

/// A topic synthesis generated by one of `DeepReadSynthesisTemplate`, stored in
/// `structuredJSON` under its own `shape`.
struct DeepReadTemplateArticle: Codable, Equatable {
    static let shapeID = "template_synthesis"

    var shape = shapeID
    var template: String
    var title: String
    var lede: String
    var sources: [Source]
    var brief: Brief?
    var qa: [Answer]?
    var debate: Debate?
    var timeline: Timeline?
    var review: Review?

    struct Source: Codable, Equatable {
        var id: Int
        var title: String
        var url: String?
        var site: String
    }

    struct Brief: Codable, Equatable {
        var points: [String]
        var background: String
        var impact: String
        var uncertain: [String]
    }

    struct Answer: Codable, Equatable {
        var question: String
        var answer: String
        var sources: [Int]
    }

    struct Debate: Codable, Equatable {
        struct Camp: Codable, Equatable {
            var stance: String
            var label: String
            var holders: [String]
            var argument: String
            var quote: String
            var quoteBy: String
            var sources: [Int]
        }
        var dispute: String
        var camps: [Camp]
        var takeaway: String
    }

    struct Timeline: Codable, Equatable {
        struct Event: Codable, Equatable {
            var date: String
            var event: String
            var turning: Bool
            var sources: [Int]
        }
        struct Turn: Codable, Equatable {
            var date: String
            var why: String
        }
        var events: [Event]
        var turns: [Turn]
    }

    struct Review: Codable, Equatable {
        struct Split: Codable, Equatable {
            var topic: String
            var views: [View]
        }
        struct View: Codable, Equatable {
            var source: Int
            var view: String
        }
        struct Spec: Codable, Equatable {
            var name: String
            var value: String
        }
        struct Score: Codable, Equatable {
            var source: Int
            var score: String
            var note: String
        }
        var verdict: String
        var consensus: [String]
        var splits: [Split]
        var specs: [Spec]
        var scores: [Score]
        var conclusion: String
    }

    var kind: DeepReadSynthesisTemplate { DeepReadSynthesisTemplate(rawValue: template) ?? .brief }

    static func decode(_ json: String?) -> DeepReadTemplateArticle? {
        guard let data = json?.data(using: .utf8),
              let article = try? JSONDecoder().decode(DeepReadTemplateArticle.self, from: data),
              article.shape == shapeID else { return nil }
        return article
    }

    func encoded() -> String? {
        (try? JSONEncoder().encode(self)).flatMap { String(data: $0, encoding: .utf8) }
    }
}

enum DeepReadTemplateWriter {
    static let maxSources = 12
    static let excerptChars = 1_200
    /// Auto mode may also keep the classic magazine pipeline.
    static let magazineChoice = "magazine"

    static func numbered(_ sources: [IOSDeepReadSource]) -> [(id: Int, source: IOSDeepReadSource)] {
        sources.filter(\.hasUsableGenerationContent).prefix(maxSources).enumerated().map { ($0.offset + 1, $0.element) }
    }

    private static func sourcesBlock(_ numbered: [(id: Int, source: IOSDeepReadSource)]) -> String {
        numbered.map { item in
            let site = DeepReadCloseReader.siteName(item.source.url) ?? item.source.kind.title
            return "[\(item.id)] \(site)｜\(item.source.title)\n"
                + IOSDeepReadSourceNormalizer.cleanMultiline(item.source.content).deepReadPrefixString(excerptChars)
        }.joined(separator: "\n\n")
    }

    // MARK: Auto pick

    static func pickPrompt(topic: String, numbered: [(id: Int, source: IOSDeepReadSource)]) -> String {
        var b = "你要为话题「\(topic)」选择最合适的深度阅读写法。只看下面的来源标题和开头，不要写文章。\n## 可选\n"
        for template in DeepReadSynthesisTemplate.concrete { b += "- \(template.rawValue)：\(template.name)，适合\(template.useWhen)\n" }
        b += "- \(magazineChoice)：经典杂志长文，适合背景复杂、需要全面梳理时间线与各方分析的重大事件\n"
        b += #"只输出 JSON：{"template":"deepread_brief","reason":"一句话理由"}"#
        b += "\n\n## 来源\n"
        b += numbered.map { "[\($0.id)] \($0.source.title)：\(IOSDeepReadSourceNormalizer.cleanMultiline($0.source.content).deepReadPrefixString(160))" }.joined(separator: "\n")
        return b
    }

    /// The chosen template, or nil for the classic magazine (also the fallback for an unreadable reply).
    static func parsePick(_ text: String) -> DeepReadSynthesisTemplate? {
        guard let json = IOSDeepReadDraftGenerator.extractJSONObject(text),
              let object = (try? JSONSerialization.jsonObject(with: Data(json.utf8))) as? [String: Any],
              let id = object["template"] as? String,
              let template = DeepReadSynthesisTemplate(rawValue: id.trimmingCharacters(in: .whitespaces)),
              template != .auto else { return nil }
        return template
    }

    // MARK: Generate

    static func prompt(_ template: DeepReadSynthesisTemplate, topic: String, numbered: [(id: Int, source: IOSDeepReadSource)]) -> String {
        var b = "你是深度阅读的编辑，要用「\(template.name)」的写法，把下面的来源整理成一篇关于「\(topic)」的中文深度阅读。\n"
        b += "## 通用要求\n- title：简体中文标题，不超过 30 字。\n- lede：80-160 字导语。\n"
        b += "- 只用来源里的事实，不编造；sources 填来源编号数组，用来标注依据。\n- 所有文字用简体中文。只输出合法 JSON，不要代码围栏和解释。\n"
        b += "## 模板要求\n"
        switch template {
        case .auto, .brief:
            b += "points 5 条要点，每条不超过 50 字；background 背景 100-200 字；impact 影响 100-200 字；uncertain 0-4 条尚未确认的说法，每条不超过 60 字。\n"
            b += #"输出：{"title":"…","lede":"…","points":["…"],"background":"…","impact":"…","uncertain":["…"]}"#
        case .qa:
            b += "questions 5-8 个读者最可能问的问题，由浅入深；q 不超过 30 字，a 80-220 字，sources 为依据的来源编号。\n"
            b += #"输出：{"title":"…","lede":"…","questions":[{"q":"…","a":"…","sources":[1,2]}]}"#
        case .debate:
            b += "dispute 核心争议不超过 80 字；camps 2-4 个阵营，stance 取 pro（支持）、con（反对）、neutral（中立或折中）；label 阵营名不超过 10 字，holders 代表人物或机构不超过 4 个，argument 主要论点不超过 160 字，quote 来源中的一句原话（没有就空字符串），quote_by 说话人，sources 来源编号；takeaway「你可以怎么看」不超过 160 字，帮读者权衡而不是替读者站队。\n"
            b += #"输出：{"title":"…","lede":"…","dispute":"…","camps":[{"stance":"pro","label":"…","holders":["…"],"argument":"…","quote":"…","quote_by":"…","sources":[1]}],"takeaway":"…"}"#
        case .timeline:
            b += "events 10-15 个时间节点，按时间先后；date 写具体日期或时间，event 不超过 60 字，turning 标记是否为转折点（总共 1-3 个），sources 来源编号；turns 解读每个转折点，why 不超过 120 字。\n"
            b += #"输出：{"title":"…","lede":"…","events":[{"date":"…","event":"…","turning":false,"sources":[1]}],"turns":[{"date":"…","why":"…"}]}"#
        case .review:
            b += "verdict 一句话总结论不超过 60 字；consensus 各家共识 3-5 条，每条不超过 40 字；splits 1-4 个分歧点，topic 不超过 10 字，views 为各来源的看法 {source 编号, view 不超过 40 字}；specs 3-8 行关键规格 {name, value}；scores 各家打分 {source 编号, score 原样写出如「4/5」「8.5」, note 不超过 20 字}，没有打分就空数组；conclusion 买不买的建议不超过 160 字。\n"
            b += #"输出：{"title":"…","lede":"…","verdict":"…","consensus":["…"],"splits":[{"topic":"…","views":[{"source":1,"view":"…"}]}],"specs":[{"name":"…","value":"…"}],"scores":[{"source":1,"score":"…","note":"…"}],"conclusion":"…"}"#
        }
        b += "\n\n## 来源\n" + sourcesBlock(numbered)
        return b
    }

    static func parse(_ text: String, template: DeepReadSynthesisTemplate, topic: String,
                      numbered: [(id: Int, source: IOSDeepReadSource)]) -> DeepReadTemplateArticle? {
        guard let json = IOSDeepReadDraftGenerator.extractJSONObject(text) ?? IOSDeepReadDraftGenerator.repairTruncatedJSON(text),
              let object = (try? JSONSerialization.jsonObject(with: Data(json.utf8))) as? [String: Any] else { return nil }
        let ids = Set(numbered.map(\.id))
        func string(_ value: Any?) -> String { ((value as? String) ?? "").trimmingCharacters(in: .whitespacesAndNewlines) }
        func strings(_ value: Any?, _ limit: Int) -> [String] { Array(((value as? [Any]) ?? []).map(string).filter { !$0.isEmpty }.prefix(limit)) }
        func objects(_ value: Any?) -> [[String: Any]] { (value as? [[String: Any]]) ?? [] }
        func int(_ value: Any?) -> Int? { (value as? Int) ?? (value as? Double).flatMap { Int(exactly: $0.rounded()) } ?? (value as? String).flatMap(Int.init) }
        func cited(_ value: Any?) -> [Int] { ((value as? [Any]) ?? []).compactMap(int).filter(ids.contains) }

        var article = DeepReadTemplateArticle(
            template: (template == .auto ? .brief : template).rawValue,
            title: string(object["title"]).isEmpty ? topic : string(object["title"]),
            lede: string(object["lede"]),
            sources: numbered.map { .init(id: $0.id, title: $0.source.title, url: $0.source.url,
                                          site: DeepReadCloseReader.siteName($0.source.url) ?? $0.source.kind.title) })
        switch template {
        case .auto, .brief:
            let points = strings(object["points"], 5)
            guard !points.isEmpty else { return nil }
            article.brief = .init(points: points, background: string(object["background"]), impact: string(object["impact"]),
                                  uncertain: strings(object["uncertain"], 4))
        case .qa:
            let answers = objects(object["questions"]).compactMap { raw -> DeepReadTemplateArticle.Answer? in
                let q = string(raw["q"]), a = string(raw["a"])
                return q.isEmpty || a.isEmpty ? nil : .init(question: q, answer: a, sources: cited(raw["sources"]))
            }
            guard !answers.isEmpty else { return nil }
            article.qa = Array(answers.prefix(8))
        case .debate:
            let camps = objects(object["camps"]).compactMap { raw -> DeepReadTemplateArticle.Debate.Camp? in
                let argument = string(raw["argument"])
                guard !argument.isEmpty else { return nil }
                let stance = ["pro", "con", "neutral"].contains(string(raw["stance"])) ? string(raw["stance"]) : "neutral"
                return .init(stance: stance, label: string(raw["label"]), holders: strings(raw["holders"], 4), argument: argument,
                             quote: string(raw["quote"]), quoteBy: string(raw["quote_by"]), sources: cited(raw["sources"]))
            }
            guard camps.count >= 2 else { return nil }
            article.debate = .init(dispute: string(object["dispute"]), camps: Array(camps.prefix(4)), takeaway: string(object["takeaway"]))
        case .timeline:
            let events = objects(object["events"]).compactMap { raw -> DeepReadTemplateArticle.Timeline.Event? in
                let event = string(raw["event"])
                return event.isEmpty ? nil : .init(date: string(raw["date"]), event: event, turning: (raw["turning"] as? Bool) ?? false,
                                                   sources: cited(raw["sources"]))
            }
            guard events.count >= 3 else { return nil }
            let turns = objects(object["turns"]).compactMap { raw -> DeepReadTemplateArticle.Timeline.Turn? in
                string(raw["why"]).isEmpty ? nil : .init(date: string(raw["date"]), why: string(raw["why"]))
            }
            article.timeline = .init(events: Array(events.prefix(15)), turns: Array(turns.prefix(3)))
        case .review:
            let verdict = string(object["verdict"])
            guard !verdict.isEmpty else { return nil }
            let splits = objects(object["splits"]).compactMap { raw -> DeepReadTemplateArticle.Review.Split? in
                let views = objects(raw["views"]).compactMap { view -> DeepReadTemplateArticle.Review.View? in
                    guard let source = int(view["source"]), ids.contains(source), !string(view["view"]).isEmpty else { return nil }
                    return .init(source: source, view: string(view["view"]))
                }
                return string(raw["topic"]).isEmpty || views.isEmpty ? nil : .init(topic: string(raw["topic"]), views: views)
            }
            let specs = objects(object["specs"]).compactMap { raw -> DeepReadTemplateArticle.Review.Spec? in
                string(raw["name"]).isEmpty || string(raw["value"]).isEmpty ? nil : .init(name: string(raw["name"]), value: string(raw["value"]))
            }
            let scores = objects(object["scores"]).compactMap { raw -> DeepReadTemplateArticle.Review.Score? in
                guard let source = int(raw["source"]), ids.contains(source), !string(raw["score"]).isEmpty else { return nil }
                return .init(source: source, score: string(raw["score"]), note: string(raw["note"]))
            }
            article.review = .init(verdict: verdict, consensus: strings(object["consensus"], 5), splits: Array(splits.prefix(4)),
                                   specs: Array(specs.prefix(8)), scores: scores, conclusion: string(object["conclusion"]))
        }
        return article
    }

    // MARK: Export

    static func markdown(_ a: DeepReadTemplateArticle) -> String {
        func refs(_ ids: [Int]) -> String { ids.isEmpty ? "" : " " + ids.map { "[\($0)]" }.joined() }
        func bullets(_ items: [String]) -> String { items.map { "- \($0)" }.joined(separator: "\n") + "\n\n" }
        var b = "# \(a.title)\n\n"
        if !a.lede.isEmpty { b += "> \(a.lede)\n\n" }
        if let brief = a.brief {
            b += "## 要点\n" + bullets(brief.points)
            if !brief.background.isEmpty { b += "## 背景\n\n\(brief.background)\n\n" }
            if !brief.impact.isEmpty { b += "## 影响\n\n\(brief.impact)\n\n" }
            if !brief.uncertain.isEmpty { b += "## 待核实\n" + bullets(brief.uncertain) }
        }
        if let qa = a.qa {
            for item in qa { b += "## \(item.question)\n\n\(item.answer)\(refs(item.sources))\n\n" }
        }
        if let debate = a.debate {
            if !debate.dispute.isEmpty { b += "## 核心争议\n\n\(debate.dispute)\n\n" }
            for camp in debate.camps {
                b += "### \(camp.label)" + (camp.holders.isEmpty ? "" : "（\(camp.holders.joined(separator: "、"))）") + "\n\n\(camp.argument)\(refs(camp.sources))\n\n"
                if !camp.quote.isEmpty { b += "> “\(camp.quote)”" + (camp.quoteBy.isEmpty ? "" : " —— \(camp.quoteBy)") + "\n\n" }
            }
            if !debate.takeaway.isEmpty { b += "## 你可以怎么看\n\n\(debate.takeaway)\n\n" }
        }
        if let timeline = a.timeline {
            b += "## 时间线\n" + bullets(timeline.events.map { "**\($0.date)**\($0.turning ? "（转折）" : "") \($0.event)\(refs($0.sources))" })
            if !timeline.turns.isEmpty { b += "## 转折点\n" + bullets(timeline.turns.map { "**\($0.date)** \($0.why)" }) }
        }
        if let review = a.review {
            b += "## 结论\n\n**\(review.verdict)**\n\n"
            if !review.consensus.isEmpty { b += "## 各家共识\n" + bullets(review.consensus) }
            for split in review.splits { b += "## 分歧：\(split.topic)\n" + bullets(split.views.map { "[\($0.source)] \($0.view)" }) }
            if !review.specs.isEmpty { b += "## 关键规格\n" + bullets(review.specs.map { "\($0.name)：\($0.value)" }) }
            if !review.scores.isEmpty { b += "## 打分\n" + bullets(review.scores.map { "[\($0.source)] \($0.score)\($0.note.isEmpty ? "" : "（\($0.note)）")" }) }
            if !review.conclusion.isEmpty { b += "## 买不买\n\n\(review.conclusion)\n\n" }
        }
        b += "## 来源\n" + bullets(a.sources.map { source in
            "[\(source.id)] \(source.site)：" + (source.url.map { "[\(source.title)](\($0))" } ?? source.title)
        })
        return b
    }
}
